# Generated by Django 5.1.5 on 2025-02-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundoimobiliario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='fundoimobiliario',
            name='ultima_atualizacao',
        ),
        migrations.RemoveField(
            model_name='fundoimobiliario',
            name='valor_em_caixa',
        ),
    ]
